import com.aylien.newsapi.*;
import com.aylien.newsapi.auth.*;
import com.aylien.newsapi.models.*;
import com.aylien.newsapi.parameters.*;
import com.aylien.newsapi.api.DefaultApi;

import java.util.Arrays;
import java.util.List;

public class Main {

    public static void main(String[] args) {
        ApiClient defaultClient = Configuration.getDefaultApiClient();

        // Configure API key authorization: app_id
        ApiKeyAuth app_id = (ApiKeyAuth) defaultClient.getAuthentication("app_id");
        app_id.setApiKey("{{current_app_id}}");

        // Configure API key authorization: app_key
        ApiKeyAuth app_key = (ApiKeyAuth) defaultClient.getAuthentication("app_key");
        app_key.setApiKey("{{current_app_key}}");

        DefaultApi apiInstance = new DefaultApi();

        List<Long> id = Arrays.asList(985744L);
        List<Long> notId = Arrays.asList(5241L, 4412L);
        String title = "startup AND (raise OR raised OR raising OR raises)";
        String body = "startup";
        String text = "startup company";
        List<String> language = Arrays.asList("en", "es", "es");
        List<String> notLanguage = Arrays.asList("fr", "pt", "it");
        String publishedAtStart = "NOW-3MONTHS/DAY";
        String publishedAtEnd = "NOW-10DAYS";
        String categoriesTaxonomy = "iab-qag";
        Boolean categoriesConfident = true;
        List<String> categoriesId = Arrays.asList("IAB15", "IAB13-1");
        List<String> notCategoriesId = Arrays.asList("IAB3-2");
        List<Integer> categoriesLevel = Arrays.asList(2);
        List<Integer> notCategoriesLevel = Arrays.asList(1, 3);
        List<String> entitiesTitleText = Arrays.asList("GNU/Linux", "Microsoft Windows");
        List<String> notEntitiesTitleText = Arrays.asList("Ireland", "Dublin");
        List<String> entitiesTitleType = Arrays.asList("Software", "Organization");
        List<String> notEntitiesTitleType = Arrays.asList("Agent", "Person");
        List<String> entitiesTitleLinksDbpedia = Arrays.asList("http://dbpedia.org/resource/Linux");
        List<String> notEntitiesTitleLinksDbpedia = Arrays.asList("http://dbpedia.org/resource/Windows");
        List<String> entitiesBodyText = Arrays.asList("GNU/Linux", "Microsoft Windows");
        List<String> notEntitiesBodyText = Arrays.asList("Trump");
        List<String> entitiesBodyType = Arrays.asList("Agent", "Person");
        List<String> notEntitiesBodyType = Arrays.asList("Software", "Organization");
        List<String> entitiesBodyLinksDbpedia = Arrays.asList("entitiesBodyLinksDbpedia_example");
        List<String> notEntitiesBodyLinksDbpedia = Arrays.asList("http://dbpedia.org/resource/Linux");
        String sentimentTitlePolarity = "negative";
        String notSentimentTitlePolarity = "positive";
        String sentimentBodyPolarity = "neutral";
        String notSentimentBodyPolarity = "negative";
        Integer mediaImagesCountMin = 2;
        Integer mediaImagesCountMax = 4;
        Integer mediaImagesWidthMin = 640;
        Integer mediaImagesWidthMax = 1024;
        Integer mediaImagesHeightMin = 480;
        Integer mediaImagesHeightMax = 800;
        Integer mediaImagesContentLengthMin = 25411;
        Integer mediaImagesContentLengthMax = 369541;
        List<String> mediaImagesFormat = Arrays.asList("JPEG", "BMP", "GIF");
        List<String> notMediaImagesFormat = Arrays.asList("PNG", "TIFF");
        Integer mediaVideosCountMin = 1;
        Integer mediaVideosCountMax = 2;
        List<Integer> authorId = Arrays.asList(36521);
        List<Integer> notAuthorId = Arrays.asList(2541);
        String authorName = "John Doe";
        String notAuthorName = "Mike Wally";
        List<Integer> sourceId = Arrays.asList(1411);
        List<Integer> notSourceId = Arrays.asList(251);
        List<String> sourceName = Arrays.asList("BBC");
        List<String> notSourceName = Arrays.asList("Fox News");
        List<String> sourceDomain = Arrays.asList("bbc.co.uk");
        List<String> notSourceDomain = Arrays.asList("foxnews.com");
        List<String> sourceLocationsCountry = Arrays.asList("US", "IE");
        List<String> notSourceLocationsCountry = Arrays.asList("IR");
        List<String> sourceLocationsState = Arrays.asList("California");
        List<String> notSourceLocationsState = Arrays.asList("Arizona");
        List<String> sourceLocationsCity = Arrays.asList("Los Angeles");
        List<String> notSourceLocationsCity = Arrays.asList("Dublin City");
        List<String> sourceScopesCountry = Arrays.asList("IE", "NG");
        List<String> notSourceScopesCountry = Arrays.asList("US", "GB");
        List<String> sourceScopesState = Arrays.asList("Co Dublin");
        List<String> notSourceScopesState = Arrays.asList("Co Wicklow");
        List<String> sourceScopesCity = Arrays.asList("Dublin City");
        List<String> notSourceScopesCity = Arrays.asList("Cork");
        List<String> sourceScopesLevel = Arrays.asList("national");
        List<String> notSourceScopesLevel = Arrays.asList("local");
        Integer sourceLinksInCountMin = 354211;
        Integer sourceLinksInCountMax = 587412;
        Integer sourceRankingsAlexaRankMin = 10;
        Integer sourceRankingsAlexaRankMax = 2500;
        List<String> sourceRankingsAlexaCountry = Arrays.asList("IE");
        Integer socialSharesCountFacebookMin = 3521;
        Integer socialSharesCountFacebookMax = 5841;
        Integer socialSharesCountGooglePlusMin = 2514;
        Integer socialSharesCountGooglePlusMax = 36521;
        Integer socialSharesCountLinkedinMin = 6521;
        Integer socialSharesCountLinkedinMax = 36521;
        Integer socialSharesCountRedditMin = 14125;
        Integer socialSharesCountRedditMax = 95412;
        Boolean cluster = false;
        String clusterAlgorithm = "kmeans";
        List<String> _return = Arrays.asList("id", "title");
        String sortBy = "published_at";
        String sortDirection = "desc";
        String cursor = "*";
        Integer perPage = 10;

        StoriesParams.Builder storiesBuilder = StoriesParams.newBuilder();

        storiesBuilder.setId(id);
        storiesBuilder.setNotId(notId);
        storiesBuilder.setTitle(title);
        storiesBuilder.setBody(body);
        storiesBuilder.setText(text);
        storiesBuilder.setLanguage(language);
        storiesBuilder.setNotLanguage(notLanguage);
        storiesBuilder.setPublishedAtStart(publishedAtStart);
        storiesBuilder.setPublishedAtEnd(publishedAtEnd);
        storiesBuilder.setCategoriesTaxonomy(categoriesTaxonomy);
        storiesBuilder.setCategoriesConfident(categoriesConfident);
        storiesBuilder.setCategoriesId(categoriesId);
        storiesBuilder.setNotCategoriesId(notCategoriesId);
        storiesBuilder.setCategoriesLevel(categoriesLevel);
        storiesBuilder.setNotCategoriesLevel(notCategoriesLevel);
        storiesBuilder.setEntitiesTitleText(entitiesTitleText);
        storiesBuilder.setNotEntitiesTitleText(notEntitiesTitleText);
        storiesBuilder.setEntitiesTitleType(entitiesTitleType);
        storiesBuilder.setNotEntitiesTitleType(notEntitiesTitleType);
        storiesBuilder.setEntitiesTitleLinksDbpedia(entitiesTitleLinksDbpedia);
        storiesBuilder.setNotEntitiesTitleLinksDbpedia(notEntitiesTitleLinksDbpedia);
        storiesBuilder.setEntitiesBodyText(entitiesBodyText);
        storiesBuilder.setNotEntitiesBodyText(notEntitiesBodyText);
        storiesBuilder.setEntitiesBodyType(entitiesBodyType);
        storiesBuilder.setNotEntitiesBodyType(notEntitiesBodyType);
        storiesBuilder.setEntitiesBodyLinksDbpedia(entitiesBodyLinksDbpedia);
        storiesBuilder.setNotEntitiesBodyLinksDbpedia(notEntitiesBodyLinksDbpedia);
        storiesBuilder.setSentimentTitlePolarity(sentimentTitlePolarity);
        storiesBuilder.setNotSentimentTitlePolarity(notSentimentTitlePolarity);
        storiesBuilder.setSentimentBodyPolarity(sentimentBodyPolarity);
        storiesBuilder.setNotSentimentBodyPolarity(notSentimentBodyPolarity);
        storiesBuilder.setMediaImagesCountMin(mediaImagesCountMin);
        storiesBuilder.setMediaImagesCountMax(mediaImagesCountMax);
        storiesBuilder.setMediaImagesWidthMin(mediaImagesWidthMin);
        storiesBuilder.setMediaImagesWidthMax(mediaImagesWidthMax);
        storiesBuilder.setMediaImagesHeightMin(mediaImagesHeightMin);
        storiesBuilder.setMediaImagesHeightMax(mediaImagesHeightMax);
        storiesBuilder.setMediaImagesContentLengthMin(mediaImagesContentLengthMin);
        storiesBuilder.setMediaImagesContentLengthMax(mediaImagesContentLengthMax);
        storiesBuilder.setMediaImagesFormat(mediaImagesFormat);
        storiesBuilder.setNotMediaImagesFormat(notMediaImagesFormat);
        storiesBuilder.setMediaVideosCountMin(mediaVideosCountMin);
        storiesBuilder.setMediaVideosCountMax(mediaVideosCountMax);
        storiesBuilder.setAuthorId(authorId);
        storiesBuilder.setNotAuthorId(notAuthorId);
        storiesBuilder.setAuthorName(authorName);
        storiesBuilder.setNotAuthorName(notAuthorName);
        storiesBuilder.setSourceId(sourceId);
        storiesBuilder.setNotSourceId(notSourceId);
        storiesBuilder.setSourceName(sourceName);
        storiesBuilder.setNotSourceName(notSourceName);
        storiesBuilder.setSourceDomain(sourceDomain);
        storiesBuilder.setNotSourceDomain(notSourceDomain);
        storiesBuilder.setSourceLocationsCountry(sourceLocationsCountry);
        storiesBuilder.setNotSourceLocationsCountry(notSourceLocationsCountry);
        storiesBuilder.setSourceLocationsState(sourceLocationsState);
        storiesBuilder.setNotSourceLocationsState(notSourceLocationsState);
        storiesBuilder.setSourceLocationsCity(sourceLocationsCity);
        storiesBuilder.setNotSourceLocationsCity(notSourceLocationsCity);
        storiesBuilder.setSourceScopesCountry(sourceScopesCountry);
        storiesBuilder.setNotSourceScopesCountry(notSourceScopesCountry);
        storiesBuilder.setSourceScopesState(sourceScopesState);
        storiesBuilder.setNotSourceScopesState(notSourceScopesState);
        storiesBuilder.setSourceScopesCity(sourceScopesCity);
        storiesBuilder.setNotSourceScopesCity(notSourceScopesCity);
        storiesBuilder.setSourceScopesLevel(sourceScopesLevel);
        storiesBuilder.setNotSourceScopesLevel(notSourceScopesLevel);
        storiesBuilder.setSourceLinksInCountMin(sourceLinksInCountMin);
        storiesBuilder.setSourceLinksInCountMax(sourceLinksInCountMax);
        storiesBuilder.setSourceRankingsAlexaRankMin(sourceRankingsAlexaRankMin);
        storiesBuilder.setSourceRankingsAlexaRankMax(sourceRankingsAlexaRankMax);
        storiesBuilder.setSourceRankingsAlexaCountry(sourceRankingsAlexaCountry);
        storiesBuilder.setSocialSharesCountFacebookMin(socialSharesCountFacebookMin);
        storiesBuilder.setSocialSharesCountFacebookMax(socialSharesCountFacebookMax);
        storiesBuilder.setSocialSharesCountGooglePlusMin(socialSharesCountGooglePlusMin);
        storiesBuilder.setSocialSharesCountGooglePlusMax(socialSharesCountGooglePlusMax);
        storiesBuilder.setSocialSharesCountLinkedinMin(socialSharesCountLinkedinMin);
        storiesBuilder.setSocialSharesCountLinkedinMax(socialSharesCountLinkedinMax);
        storiesBuilder.setSocialSharesCountRedditMin(socialSharesCountRedditMin);
        storiesBuilder.setSocialSharesCountRedditMax(socialSharesCountRedditMax);
        storiesBuilder.setCluster(cluster);
        storiesBuilder.setClusterAlgorithm(clusterAlgorithm);
        storiesBuilder.set_return(_return);
        storiesBuilder.setSortBy(sortBy);
        storiesBuilder.setSortDirection(sortDirection);
        storiesBuilder.setCursor(cursor);
        storiesBuilder.setPerPage(perPage);

        try {
            Stories result = apiInstance.listStories(storiesBuilder.build());
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling DefaultApi#listStories");
            e.printStackTrace();
        }
    }
}
